### ISSUE TITLE
Tool does not erase flash before upload

### ISSUE THREAD

**Issue by mikevanis** [interactionresearchstudio/esptool-python-gui#1]
If it does, does that mean we have to re-upload the partition?

**Comment by andysheen** [comment]
I don't think so, as were not doing anything special outside the application. Potentially check this with a sketch with OTA and see if it works

**Comment by mikevanis** [comment]
Cool, ATM we're not supporting OTA, shall we just erase it all before flashing? Would just need to change the `esptool_options` array at the start of the main python file.

**Comment by andysheen** [comment]
I think that makes sense for this version
