### ISSUE TITLE
Serial port selector should auto-select familar device patterns (eg /dev/cu.SLAB_USBtoUART)

### ISSUE THREAD

**Issue by davidchatting** [interactionresearchstudio/esptool-python-gui#16]

**Comment by andysheen** [comment]
Is there the similar we can do for windows? otherwise it seems a little bias to a small cross section of our users..

**Comment by davidchatting** [comment]
I don't think there is is there? but for 10 minutes coding I think it's worth it - at the moment it defaults to something that's always wrong (for me)

**Comment by andysheen** [comment]
sounds good 👍

**Comment by mikevanis** [comment]
We should stop opening all ports to test that they're there. We should also select the highest com port on windows.
