### ISSUE TITLE
Fix interaction between Upload and Debug buttons

### ISSUE THREAD

**Issue by davidchatting** [interactionresearchstudio/esptool-python-gui#18]
Suggest that:
1) If we are using the blue to draw attention to upload, let's not use the blue highlight on Debug - that can be a normal button like refresh
2) Debug should not disable Upload - if you press Upload it should just manage the transistion (by stopping debug)
3) Pressing Debug for second time should not stop it

Alternatively, if the debug stream is fairly quite (as I think it is?) - I would suggest defaulting to that (and loosing the Debug button) so debug will by default be coming up in the log - then when you press upload it switches over to that for as long as the upload process and then switches back to debug < this is option I think I prefer

**Comment by mikevanis** [comment]
Will also stop opening all serial ports to test that they're there.

**Comment by mikevanis** [comment]
On Windows, we should just pick the highest com port.

**Comment by mikevanis** [comment]
We shouldn't disable the upload button. Should stop debug if upload is clicked. Should change text from Start Debug to Stop Debug when active.
