### ISSUE TITLE
No action text on OSX 10.14.6

### ISSUE THREAD

**Issue by andysheen** [interactionresearchstudio/esptool-python-gui#2]
See attached image

<img width="305" alt="Screenshot 2020-08-10 at 10 15 22" src="https://user-images.githubusercontent.com/20442164/89767764-7cdcb000-daf2-11ea-9566-06a579d541fd.png">

**Comment by mikevanis** [comment]
Must be something to do with Mojave default colours. Will try to explicitly set the colour of buttons like described in this [SO thread](https://stackoverflow.com/questions/11340765/default-window-colour-tkinter-and-hex-colour-codes).

**Comment by andysheen** [comment]
commit https://github.com/interactionresearchstudio/esptool-python-gui/commit/f8ae60d711294cec0f1f5514a406188b43e33f80 fixed this for now.
