### ISSUE TITLE
[Bug] Quits unexpectedly

### ISSUE THREAD

**Issue by Nickdonati** [interactionresearchstudio/esptool-python-gui#27]
I'm using Macbook Pro M1, Sonoma 14.2. The Yo-Yo firmware uploader crashes soon after opening. Didn't have a chance to try on Windows

**Comment by mikevanis** [comment]
We're working on a solution to this. Seems like this only happens on Sonoma.

**Comment by mikevanis** [comment]
Fixed in latest release
